
SELECT
    MI.BDCODMATR,
    A.BDNOMEALU,
    A.BDCODALU,
    COUNT(*) AS TOTAL_DISC,
    --SUM(D.BDVALORCRED) AS TOTAL_CREDITOS,
    MAX(D.BDVALORCRED) AS MAIOR_CREDITO
    --MIN(D.BDVALORCRED) AS MENOR_CREDITO
FROM TMATRICULA_ITEM MI
JOIN TMATRICULA M ON (MI.BDCODMATR = M.BDCODMATR)
JOIN TALUNO A ON (A.BDCODALU = M.BDCODALU)
JOIN TDISCIPLINA D ON (D.BDCODDISC = MI.BDCODDISC)
GROUP BY MI.BDCODMATR, A.BDCODALU, A.BDNOMEALU
HAVING MAX(D.BDVALORCRED) > 1000


SELECT
    D.BDCODPROF,
    P.BDNOMEPROF,
    COUNT(*) AS TOTAL_DISC
FROM TDISCIPLINA D
JOIN TPROFESSOR P ON (P.BDCODPROF = D.BDCODPROF)
WHERE
/*NOT*/ EXISTS (
        SELECT MI.*
        FROM tmatricula_item MI
        WHERE MI.BDCODDISC = D.BDCODDISC
    )
GROUP BY D.BDCODPROF, P.BDNOMEPROF

--- ALTERNATIVA 2 --------

SELECT
    D.BDCODPROF,
    COUNT(*)
FROM (
    SELECT
        MI.BDCODDISC
    FROM TMATRICULA_ITEM MI
    GROUP BY MI.BDCODDISC
) DISC
JOIN tdisciplina D ON (D.bdcoddisc = DISC.BDCODDISC)
GROUP BY D.BDCODPROF
