
CREATE TABLE TPESSOA (
    BDCODPESSOA INTEGER PRIMARY KEY,
    BDNOMEPESSOA DN_NOME,
    BDSOBRENOMEPESSOA DN_SOBRENOME
);

CREATE TABLE TSALA (
    BDCODSALA INTEGER PRIMARY KEY,
    BDNOMESALA DN_NOME,
    BDLOTACAOMAXIMASALA DN_LOTACAOMAXIMA,
    BDLOTACAOATUALSALA DN_LOTACAOATUAL
);

CREATE TABLE TESPACOCAFE (
    BDCODESPACOCAFE INTEGER PRIMARY KEY,
    BDNOMEESPACOCAFE DN_NOME,
    BDLOTACAOMAXIMASALA DN_LOTACAOMAXIMA,
    BDLOTACAOATUALSALA DN_LOTACAOATUAL
);

drop table tetapa;
CREATE TABLE TETAPA (
    BDCODPESSOA INTEGER NOT NULL,
    BDCODSALA INTEGER NOT NULL,
    BDCODESPACOCAFE INTEGER NOT NULL,
    BDNUMETAPA DN_NUMETAPA,
    CONSTRAINT PK_TETAPA PRIMARY KEY (BDCODPESSOA, BDCODSALA, BDCODESPACOCAFE)
);


ALTER TABLE TETAPA
    ADD CONSTRAINT FK_TETAPA_TPESSOA FOREIGN KEY (BDCODPESSOA)
        REFERENCES TPESSOA(BDCODPESSOA);

ALTER TABLE TETAPA
    ADD CONSTRAINT FK_TETAPA_TSALA FOREIGN KEY (BDCODSALA)
        REFERENCES TSALA(BDCODSALA);

ALTER TABLE TETAPA
    ADD CONSTRAINT FK_TETAPA_TESPACOCAFE FOREIGN KEY (BDCODESPACOCAFE)
        REFERENCES TESPACOCAFE(BDCODESPACOCAFE);