INSERT INTO TPESSOA (BDNOMEPESSOA, BDSOBRENOMEPESSOA) VALUES ('João', 'Silva');
INSERT INTO TPESSOA (BDNOMEPESSOA, BDSOBRENOMEPESSOA) VALUES ('Maria', 'Oliveira');
INSERT INTO TPESSOA (BDNOMEPESSOA, BDSOBRENOMEPESSOA) VALUES ('Carlos', 'Santos');
INSERT INTO TPESSOA (BDNOMEPESSOA, BDSOBRENOMEPESSOA) VALUES ('Ana', 'Pereira');
INSERT INTO TPESSOA (BDNOMEPESSOA, BDSOBRENOMEPESSOA) VALUES ('Lucas', 'Souza');

INSERT INTO TSALA (BDNOMESALA, BDLOTACAOMAXIMASALA, BDLOTACAOATUALSALA) VALUES ('Sala 101', 30, 0);
INSERT INTO TSALA (BDNOMESALA, BDLOTACAOMAXIMASALA, BDLOTACAOATUALSALA) VALUES ('Sala 102', 25, 0);
INSERT INTO TSALA (BDNOMESALA, BDLOTACAOMAXIMASALA, BDLOTACAOATUALSALA) VALUES ('Sala de Reunião A', 10, 0);
INSERT INTO TSALA (BDNOMESALA, BDLOTACAOMAXIMASALA, BDLOTACAOATUALSALA) VALUES ('Laboratório 1', 20, 0);
INSERT INTO TSALA (BDNOMESALA, BDLOTACAOMAXIMASALA, BDLOTACAOATUALSALA) VALUES ('Auditório', 100, 0);

INSERT INTO TESPACOCAFE (BDNOMEESPACOCAFE, BDLOTACAOMAXIMAESPACOCAFE, BDLOTACAOATUALESPACOCAFE) VALUES ('Café Central', 50, 0);
INSERT INTO TESPACOCAFE (BDNOMEESPACOCAFE, BDLOTACAOMAXIMAESPACOCAFE, BDLOTACAOATUALESPACOCAFE) VALUES ('Espaço Gourmet', 40, 0);
INSERT INTO TESPACOCAFE (BDNOMEESPACOCAFE, BDLOTACAOMAXIMAESPACOCAFE, BDLOTACAOATUALESPACOCAFE) VALUES ('Cantina Sul', 30, 0);
INSERT INTO TESPACOCAFE (BDNOMEESPACOCAFE, BDLOTACAOMAXIMAESPACOCAFE, BDLOTACAOATUALESPACOCAFE) VALUES ('Varanda do Café', 20, 0);
INSERT INTO TESPACOCAFE (BDNOMEESPACOCAFE, BDLOTACAOMAXIMAESPACOCAFE, BDLOTACAOATUALESPACOCAFE) VALUES ('Coffee Lounge', 35, 0);

INSERT INTO TETAPA (BDCODPESSOA, BDCODSALA, BDCODESPACOCAFE, BDNUMETAPA) VALUES (1, 1, 1, 1);
INSERT INTO TETAPA (BDCODPESSOA, BDCODSALA, BDCODESPACOCAFE, BDNUMETAPA) VALUES (2, 2, 2, 2);
INSERT INTO TETAPA (BDCODPESSOA, BDCODSALA, BDCODESPACOCAFE, BDNUMETAPA) VALUES (3, 3, 3, 1);
INSERT INTO TETAPA (BDCODPESSOA, BDCODSALA, BDCODESPACOCAFE, BDNUMETAPA) VALUES (4, 4, 4, 2);
INSERT INTO TETAPA (BDCODPESSOA, BDCODSALA, BDCODESPACOCAFE, BDNUMETAPA) VALUES (5, 5, 5, 1);
