create view VW_DISCIPLINAS (
    CODIGO_MATRICULA,
    CODIGO_DISCIPLINA,
    DESCR_DISCIPLINA,
    VALOR_CRED
)
as
select
    MI.BDCODMATR,
    MI.BDCODDISC,
    D.BDNOMEDISC,
    D.BDVALORCRED
from TMATRICULA_ITEM MI
JOIN TDISCIPLINA D ON (D.BDCODDISC = MI.BDCODDISC)

-- Usage
-- SELECT * FROM VW_DISCIPLINAS