SELECT *
FROM TALUNO ALU
JOIN TCIDADE CID ON
(CID.BDCODCID = ALU.BDCODCID)

SELECT
    MAT.BDCODMATR,
    MAT.BDCODALU,
    ALU.BDNOMEALU,
    ALU.BDFONEALU,
    CID.BDNOMECID,
    CID.BDUF
FROM TMATRICULA MAT
JOIN TALUNO ALU ON
(ALU.BDCODALU = MAT.BDCODALU)
JOIN TCIDADE CID ON
(CID.BDCODCID = ALU.BDCODCID)


SELECT
    D.*,
    P.bdnomeprof
FROM TDISCIPLINA D
JOIN TPROFESSOR P ON (D.BDCODPROF = P.BDCODPROF)
JOIN TCIDADE C ON (C.BDCODCID = P.BDCODCID)
WHERE
    UPPER(C.BDUF) = 'SC'


SELECT * FROM (
    SELECT
        A.BDNOMEALU as nome,
        A.BDFONEALU as telefone
    FROM taluno A
    UNION ALL
    SELECT
        P.BDNOMEPROF,
        P.BDFONE
    FROM TPROFESSOR P
) ORDEM
order BY ORDEM.nome
 collate win_ptbr


SELECT MAX(BDCODALU)
FROM TALUNO

SELECT MIN(BDNOMEALU) -- Mais cedo no alfabeto
FROM TALUNO

SELECT COUNT(*)
FROM TALUNO

SELECT AVG(BDCODALU)
FROM TALUNO

SELECT SUM(BDCODALU)
FROM TALUNO

SELECT
    a.bdcodcid,
    c.bdnomecid,
    count(*)
FROM TALUNO a
left join tcidade c on (c.bdcodcid = a.bdcodcid)
group by a.bdcodcid, c.bdnomecid