--------------------------------------------------

DROP TABLE TCIDADE
CREATE TABLE TCIDADE (
    BDCODCID    INTEGER,
    BDNOMECID   VARCHAR(84),
    BDUF        CHAR(2)
);

ALTER TABLE TCIDADE DROP BDCODCID
ALTER TABLE TCIDADE ADD BDCODCID INTEGER NOT NULL

ALTER TABLE TCIDADE ADD
CONSTRAINT PK_TCIDADE PRIMARY KEY (BDCODCID)

--------------------------------------------------

DROP TABLE TALUNO
CREATE TABLE TALUNO (
    BDCODALU      INTEGER PRIMARY KEY NOT NULL,
    BDNOMEALU     VARCHAR(177),
    BDENDERECOALU VARCHAR(255),
    BDCODCID      INTEGER,
    BDFONEALU     CHAR(15)
)

ALTER TABLE TALUNO ADD
CONSTRAINT FK_TCIDADE_ALUNO FOREIGN KEY(BDCODCID)
REFERENCES TCIDADE(BDCODCID)

--------------------------------------------------

DROP TABLE TPROFESSOR
CREATE TABLE TPROFESSOR (
    BDCODPROF       INTEGER PRIMARY KEY NOT NULL,
    BDNOMEPROF      VARCHAR(197),
    BDFONE          VARCHAR(15),
    BDENDERECOPROF  VARCHAR(506),
    BDCODCID        INTEGER
)

ALTER TABLE TPROFESSOR ADD
CONSTRAINT FK_TCIDADE_PROFESSOR FOREIGN KEY(BDCODCID)
REFERENCES TCIDADE(BDCODCID)

--------------------------------------------------

DROP TABLE TDISCIPLINA
CREATE TABLE TDISCIPLINA (
    BDCODDISC   INTEGER primary KEY NOT NULL,
    BDNOMEDISC  VARCHAR(206),
    BDCODPROF   INTEGER
)

ALTER TABLE TDISCIPLINA ADD
CONSTRAINT FK_TPROFESSOR_DISCIPLINA FOREIGN KEY(BDCODPROF)
REFERENCES TPROFESSOR(BDCODPROF)

--------------------------------------------------

DROP TABLE TMATRICULA
CREATE TABLE TMATRICULA (
    BDCODMATR   INTEGER PRIMARY KEY NOT NULL,
    BDCODALU    INTEGER
)

ALTER TABLE TMATRICULA ADD
CONSTRAINT FK_TALUNO_MATRICULA FOREIGN KEY(BDCODALU)
REFERENCES TALUNO(BDCODALU)

--------------------------------------------------

DROP TABLE TMATRICULA_ITEM
CREATE TABLE TMATRICULA_ITEM (
    BDCODMATR INTEGER NOT NULL,
    BDCODDISC INTEGER NOT NULL,
    PRIMARY KEY(BDCODMATR, BDCODDISC)
)

ALTER TABLE TMATRICULA_ITEM ADD
CONSTRAINT FK_TMATRICULA_MATRICULA_ITEM FOREIGN KEY(BDCODMATR)
REFERENCES TMATRICULA(BDCODMATR)

ALTER TABLE TMATRICULA_ITEM ADD
CONSTRAINT FK_TDISCIPLINA_MATRICULA_ITEM FOREIGN KEY(BDCODDISC)
REFERENCES TDISCIPLINA(BDCODDISC)
